BACKPORT: seccomp: add filter_count field for KernelSU
• KernelSU requires struct seccomp to have atomic_t filter_count ,
but this field is missing on NON-GKI kernels.

Adding the field fixes build errors such as:

 error: no member named 'filter_count' in 'struct seccomp'

Reference: tiann/KernelSU#2708
Actual Commit: https://github.com/GrapheneOS-Archive/kernel_common-5.10/commit/c818c03b661cd769e035e41673d5543ba2ebda64

Signed-off-by: Kees Cook <keescook@chromium.org>
Signed-off-by: Rve27 <rve27github@gmail.com>
Signed-off-by: RizkyMaulana58 <carlotta.montelli.0201@gmail.com>